# Generated by Django 4.1.6 on 2023-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sellanimal_purchaseanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseanimal',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
