# Generated by Django 4.1.6 on 2023-04-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_animal_is_for_sale_animal_price_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transaction_id',
        ),
    ]
