# Generated by Django 4.1.6 on 2023-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_animal_price_remove_purchase_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseanimal',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sellanimal',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
