# Generated by Django 4.1.6 on 2023-04-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_purchase_animal_alter_purchaseanimal_animal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellanimal',
            unique_together={('animal', 'is_sold')},
        ),
    ]
