# Generated by Django 4.1.6 on 2023-04-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sellanimal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellanimal',
            unique_together=set(),
        ),
    ]
